#!/bin/bash

## 定義檔案列表
file_List=$(cat /backup_sh/List_new)
file_Logic3=$(cat /backup_sh/List_Logic3)
# 掛載檢查函數
function check_and_mount {
    mount_point=$1
    device_or_share=$2
    mount "$device_or_share" "$mount_point"
    if ! mount | grep -q "$mount_point"; then
        echo "掛載失敗：$mount_point"
        exit 1
    fi
}

# 主程序
case "${1}" in
    "Logic2")
        echo "開始處理 Logic2 任務..."
        
        # 掛載設備
        check_and_mount /mnt/sdc1 /dev/sdc1
        check_and_mount /backup_sh/snas2 192.168.1.9:/volume1/RD_HOME

        # 同步檔案
        for i in ${file_List[@]}; do
            echo "同步檔案：$i"
            rsync -av /backup_sh/snas2/old_ws_Backup/"$i" /mnt/sdc1/Old_Project1/Logic2 >> /backup_sh/log/$(date +%Y%m%d)_CP_Logic2.log
        done

        # 複製指定目錄
        rsync -av /mnt/sdc1/Old_home/mitch/Project/R1100 /mnt/sdc1/Old_Project1/Logic2
        rsync -av /mnt/sdc1/Old_home/mitch/Project/r186 /mnt/sdc1/Old_Project1/Logic2
        rsync -av /mnt/sdc1/Old_home/mitch/Project/R8822 /mnt/sdc1/Old_Project1/Logic2

        echo -e "\e[33mLogic2 檔案同步完成！\e[0m"

        # 卸載掛載點
        umount -l /backup_sh/snas2
        umount -l /mnt/sdc1
        ;;
    "Logic3")
        echo "開始處理 Logic3 任務..."

        # 掛載設備
        check_and_mount /mnt/sdc1 /dev/sdc1
        check_and_mount /backup_sh/snas2 192.168.1.9:/volume1/RD_HOME

        # 同步檔案
        for i in ${file_Logic3[@]}; do
            echo "同步檔案：$i"
            rsync -av /backup_sh/snas2/old_ws_Backup/"$i" /mnt/sdc1/Old_Project1/Logic3 >> /backup_sh/log/$(date +%Y%m%d)_CP_Logic3.log
        done

        echo -e "\e[33mLogic3 檔案同步完成！\e[0m"

        # 卸載掛載點
        umount -l /backup_sh/snas2
        umount -l /mnt/sdc1
        ;;
    *)
        echo "用法：$0 {Logic2|Logic3}"
        exit 1
        ;;
esac

