#!/bin/bash

hs=($(awk '!/^#/ && $1 != "127.0.0.1" {print $1}' /backup_sh/log/active_hosts_20241206.log))

log_dir="/backup_sh/log"
active_log="$log_dir/active_hosts_$(date +%Y%m%d).log"
active_name_log="$log_dir/active_hosts_name_$(date +%Y%m%d).log"

#mkdir -p "$log_dir"

#> "$active_log"
#> "$active_name_log"

for i in "${hs[@]}"; do
	rsh $i 'hostname && w'
#    if ping -c 3 -W 1 "$i" >> /dev/null 2>&1; then
#        echo "$i is online" >> "$active_log"
#    else
#        echo "$i is still offline"
#    fi
done

#if [ -s "$active_log" ]; then
#    while read -r ip; do
#        grep "$ip" /etc/hosts >> "$active_name_log"
#    done < <(awk '{print $1}' "$active_log")
#else
#    echo "No active hosts recorded in $active_log"
#fi

