#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

services=("ypbind" "autofs" "nfs")

for i in ${services[@]}; do
	if service $i status >> /dev/null 2>&1; then
		echo "service $i is Health"
	else
		echo "service $i is Dead"
	fi
done
