#!/bin/bash

YELLOW="\e[1;33m"
CYAN="\e[1;36m"
GREEN="\e[1;32m"
RESET="\e[0m"

echo -e "${YELLOW}Show Server Basic Information${RESET}"
echo -e "\n============ ${CYAN}Starting to check server information${YELLOW} [$(hostname)]${RESET} at ${CYAN}$(date +%Y/%m/%d)${RESET} ============\n"

show_info() {
    echo -e "${GREEN}$1: ${YELLOW}$2${RESET}"
}

show_info "Hostname" "$(hostname)"
show_info "CPU Model" "$(awk -F ': ' '/model name/{print $2; exit}' /proc/cpuinfo)"
show_info "CPU Cores" "$(nproc)"
show_info "Memory" "$(awk '/MemTotal/ {printf "%.2f GiB", $2 / 1048576}' /proc/meminfo)"
show_info "IP Addresses" "$(hostname -I)"
show_info "OS" "$(cat /etc/redhat-release)"
show_info "OS Install Time" "$(rpm -qa basesystem --qf '%{installtime:date}\n')"
show_info "Citrix Release" "2203"
show_info "Server UP Time" "$(uptime)"
show_info "System Boot Time" "$(who -b)"

echo -e "\n============ \e[1;36mShow Server Memory Useage\e[0m at \e[1;32m$(date +%Y/%m/%d)\e[0m ============\n"
free -h

echo -e "\n============ \e[1;36mShow Server HardDisk Device\e[0m at \e[1;32m$(date +%Y/%m/%d)\e[0m ============\n"
#df -h | grep ^'/dev/' | awk '
df -h | grep -v ':/\|tmpfs' | awk '
BEGIN {
    red="\033[0;31m";
    reset="\033[0m";
    printf "%-20s %-10s %-10s %-10s %-10s %-20s\n", "Filesystem", "Size", "Used", "Avail", "Use%", "Mounted on";
}
NR>1 {
    used=$5;
    gsub("%", "", used);
    if (used > 50) {
        printf "%-20s %-10s %-10s %-10s %s%-9s%s %-20s\n", $1, $2, $3, $4, red, $5, reset, $6;
    } else {
        printf "%-20s %-10s %-10s %-10s %-10s %-20s\n", $1, $2, $3, $4, $5, $6;
    }
}'

df -h | grep ^'/dev/' | grep -v "^Filesystem" | while read output; do
    over_space=50
    usep=$(echo $output | awk '{ print $5 }' | sed 's/%//g')
    partition=$(echo $output | awk '{ print $1 }')
    mountpoint=$(echo $output | awk '{ print $6 }')
    if [ "$usep" -ge "$over_space" ]; then
        echo -e "\n\e[1;31mWarning: The partition \"$partition\" (mounted on \"$mountpoint\") is almost full. Used: $usep%\e[0m"
    fi
done

echo -e "\n"

echo -e "\e[1;33m##########################################\e[0m"
echo -e "User\t\tTotal CPU Usage\tTotal Memory Usage"; for i in $(ps aux | awk '{print $1}' | grep -Ei 'A9812|nis|DPU' | sort --unique); do
    ps -u $i -o %cpu,%mem --no-headers | awk -v user=$i 'BEGIN {green="\033[32m"; reset="\033[0m"} {cpu+=$1; mem+=$2} END {print green user reset"\t" cpu "%\t\t" mem "%"}';
done


echo -e "\n"

